project_name: projeto-korp
project_dir: /opt/projeto-korp

docker_network: korp-network

app_container: http-server-projeto-korp
nginx_container: nginx-proxy
prometheus_container: prometheus
grafana_container: grafana
nginx_exporter_container: nginx-exporter

nginx_port: 80

repository_url: "https://github.com/BortolosoA/terraform-project.git"
repository_branch: main